language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

env: 
  - ANDROID_COMPILE_SDK=28 ANDROID_BUILD_TOOLS=28.0.3 GRADLE_VERSION=4.10.3
  - ANDROID_COMPILE_SDK=29 ANDROID_BUILD_TOOLS=29.0.3 GRADLE_VERSION=5.6.4

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull -t alvisisme/android-sdk:$ANDROID_COMPILE_SDK-$ANDROID_BUILD_TOOLS-$GRADLE_VERSION --build-arg ANDROID_COMPILE_SDK=$ANDROID_COMPILE_SDK --build-arg ANDROID_BUILD_TOOLS=$ANDROID_BUILD_TOOLS --build-arg GRADLE_VERSION=$GRADLE_VERSION .
  - docker push alvisisme/android-sdk:$ANDROID_COMPILE_SDK-$ANDROID_BUILD_TOOLS-$GRADLE_VERSION

notifications:
  email:
    recipients:
      - alvisisme@163.com
    on_success: never
    on_failure: always